export enum SocketAction {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_GAME = 'JOIN_GAME',
  UPDATE_COLOR = 'UPDATE_COLOR',
  MOVE = 'MOVE',
  GET_ROOM_INFO = 'GET_ROOM_INFO',
  GET_MY_CARDS = 'GET_MY_CARDS',
}
export enum SocketListner {
  ROOM_CREATED = 'ROOM_CREATED',
  PLAYER_MESSAGE = 'PLAYER_MESSAGE',
  ERROR_MESSAGE = 'ERROR_MESSAGE',
  ROOM_INFO = 'ROOM_INFO',
  MY_CARD = 'MY_CARD',
}
